### ISSUE TITLE
glfwSetFramebufferSizeCallback mssing in the wrapper

### ISSUE THREAD

**Issue by SaculRennorb** [Ultz/Silk.NET#207]
I'd say this isn't necessarily a bug, nor is it a feature request.
I was just wondering about the reason why some of the glfw functions aren't wrapped in Silk.net.glfw and if there was a way to load them anyways?
I was specifically looking for `glfwSetFramebufferSizeCallback` which I presume would be something like `GLFW.SetFramebufferSizeCallback` in the wrapper. I see you got some of the callback setters in there like windowResize / Refresh, so why not all of them?

**Comment by Perksey** [comment]
Hey there, thanks for using Silk.NET!

Yeah, we only really exposed what we needed for Silk.NET.Windowing, however that has led to us leaving out some really handy functions. In 2.0, if all goes well we'll switch over to auto-generate the GLFW bindings from the official C headers instead of manually writing them like we do at the moment.

In the meantime, however, you can use the following API to load functions we don't expose:

## A hacky workaround
```cs
// declarations
public delegate void SetFramebufferSizeCallback(WindowHandle* window, int w, int h);
public delegate SetFramebufferSizeCallback glfwSetFramebufferSizeCallback(WindowHandle* window, SetFramebufferSizeCallback callback);
public glfwSetFramebufferSizeCallback _glfwSetFramebufferSizeCallback;

// in some load function
_someGlfwInstance = Glfw.GetApi();
_glfwSetFramebufferSizeCallback = _someGlfwInstance.Library.LoadFunction<glfwSetFramebufferSizeCallback>("glfwSetFramebufferSizeCallback");

// how to use
_glfwSetFramebufferSizeCallback(myWindowHandle, myCallback);
```

## Alternatively...
Now that is really overly complicated, so your better option is probably just to **contribute a PR exposing the function**. Pretty simple to do, simply take a look at [Glfw.cs](https://github.com/Ultz/Silk.NET/blob/master/src/Windowing/Silk.NET.GLFW/Glfw.cs#L3243) to see how similar functions are exposed, and then PR in a change adding glfwSetFramebufferSizeCallback!

This will be included in the July 2020 update slated to release on July 3rd if it's merged in before then.

**Comment by SaculRennorb** [comment]
ty very much, I'll look into it and maybe make a pr.

**Comment by Perksey** [comment]
Awesome, thanks in advance!
