### ISSUE TITLE
Create property per button and axis

### ISSUE THREAD

**Issue by mikart143** [Ultz/Silk.NET#69]
- [x] I have definitely checked that there are no proposals for this already in the [proposals folder](https://github.com/Ultz/Silk.NET-Docs)

# Summary of feature
It would be nice if we can get e.g Gamepads[0].Buttons.A vs Gamepads[0].Buttons[0]
The same for Joystick. Non standard buttons could be available in Buttons.Others[number]

# Comments

**Comment by Perksey** [comment]
I can definitely see the appeal of this, but I don't think we can implement it as properties. We'd probably have to do `Gamepads[0].Buttons.GetA()`. Is this still desirable?

**Comment by mikart143** [comment]
It would be great :D I am looking forward to see this in library

**Comment by copygirl** [comment]
Is there a standard for naming gamepad buttons?

**Comment by Perksey** [comment]
If you mean an industry-defined standard, no. The agreed-upon proposal for Silk.NET's button names are available here: https://github.com/Ultz/Silk.NET/blob/master/documentation/proposals/Proposal%20-%20Input.md#buttonname

**Comment by copygirl** [comment]
So the same `ButtonName` may refer to buttons in different physical locations?

And since said enum exists, what about `Gamepads[0].Buttons[ButtonName.A]`?

**Comment by Perksey** [comment]
Ah right. The ButtonName enum is mapped to its GLFW index, so it's mapped to whatever physical button GLFW maps it to :D 

The only reason it's `Gamepads[0].Buttons[(int) ButtonName.A]` and not `Gamepads[0].Buttons[ButtonName.A]` is because the `IReadOnlyList<Button>` interface requires an int indexer, and I'm not sure if we want to create our own interfaces for each `IReadOnlyList` usage just so we can have these indexers.

When extension everything is added, we will consider adding strong-typed indexes. See also: https://github.com/dotnet/csharplang/issues/192

**Comment by copygirl** [comment]
Oh, I was assuming `Buttons[int]` would be accessing a button by the index it's exposed as through the.. driver, I assume? And `Buttons[ButtonName]` would instead change depending on layout. Such that, for example, `0 => ButtonName.A` on XBox-style controllers, but `ButtonName.B` on Nintendo or `ButtonName.X` on PlayStation controllers. (Though, then there's Triangle and Square, ...)

**Comment by Perksey** [comment]
Yeah we use Xbox's button names, and the indices of all standard buttons match up with the ButtonName enum in order to be a conformant implementation of our Input API. An input backend may define more non-standard buttons if they're available, though.
