### ISSUE TITLE
More examples (compute, 2D charts)

### ISSUE THREAD

**Issue by DevTechProfile** [Ultz/Silk.NET#77]
I would like to get to know your library. But I need more examples, much more. 

* hardware accelerated 2D charts (is that possible)
* what to do to build a fully working 3D control like HelixViewPort3D
* compute stuff, which algorithms can be accelerated using the GPU
* what about shader compiler

**Comment by Perksey** [comment]
Those are all very specific requests.

- I don't even know where to begin with HW accelerated 2D charts.
- We don't support WPF, so that's a no-go.
- Will definitely consider adding some compute examples once we have OpenCL in!
- Shader compilers are included in the graphics APIs.

Out of curiousity, how familiar are you with OpenGL?
